apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
  namespace: devlopment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-demo
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
      - image: ShiquanLi/jenkins-demo:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: jenkins-demo
        ports:
        - containerPort：80
          name: http
        env:
        - name: branch
          value: <BRANCH_NAME>
